version: '2'

services:
  backend:
    image: 'docker-spring:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
#     These env variables are used in application.properties
      - POSTGRES_DB=docker-spring
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
#      using following variables will be directly used by ignoring application.properties
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/docker-spring
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - 8080
    ports:
      - 8080:8080
  db:
    image: 'postgres:latest'
    container_name: docker-spring-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=docker-spring
volumes:
  pgdata: