version: '2'

services:
  backend:
    image: 'docker-spring:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/docker-spring
      - SPRING_DATASOURCE_USERNAME=docker
      - SPRING_DATASOURCE_PASSWORD=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - 8080
    ports:
      - 8080:8080
  db:
    image: 'postgres:latest'
    container_name: docker-spring-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker-spring